#!/usr/bin/env python3
"""
Read catalog/*.yml files and generate a C source file with the
catalog data embedded as a single JSON blob.

The JSON is included via xxd-style byte array so no string escaping
is needed.  At runtime, the extension parses the JSON once during init.
"""

import json
import os
import sys
import yaml


def main():
    if len(sys.argv) < 3:
        print(f"usage: {sys.argv[0]} <catalog_dir> <output.c>", file=sys.stderr)
        sys.exit(1)

    catalog_dir, output_path = sys.argv[1], sys.argv[2]

    entries = []
    for dialect in sorted(os.listdir(catalog_dir)):
        dialect_dir = os.path.join(catalog_dir, dialect)
        if not os.path.isdir(dialect_dir):
            continue
        if dialect.startswith(".") or dialect == "__pycache__":
            continue
        for fname in sorted(os.listdir(dialect_dir)):
            if not fname.endswith(".yml"):
                continue
            path = os.path.join(dialect_dir, fname)
            with open(path) as f:
                spec = yaml.safe_load(f)

            params = {}
            where_fragments = {}
            for pname, pspec in spec.get("parameters", {}).items():
                params[pname] = {
                    "type": pspec.get("type", "string"),
                    "required": pspec.get("required", False),
                    "description": pspec.get("description", ""),
                }
                if "where" in pspec:
                    where_fragments[pname] = pspec["where"]

            entries.append({
                "dialect": spec.get("dialect", dialect),
                "name": spec.get("name", fname.replace(".yml", "")),
                "description": spec.get("description", ""),
                "sql": spec.get("sql", "").rstrip(),
                "parameters": params,
                "where_fragments": where_fragments,
            })

    blob = json.dumps(entries, indent=2)
    blob_bytes = blob.encode("utf-8")

    # Generate C source with the JSON as a byte array
    with open(output_path, "w") as f:
        f.write("/* Auto-generated by catalog/embed_catalog.py — do not edit */\n\n")
        f.write(f"const unsigned int blobodbc_catalog_json_len = {len(blob_bytes)};\n\n")
        f.write("const unsigned char blobodbc_catalog_json[] = {\n")

        for i in range(0, len(blob_bytes), 16):
            chunk = blob_bytes[i:i+16]
            hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"    {hex_vals},\n")

        f.write("    0x00  /* NUL terminator */\n")
        f.write("};\n")

    print(f"Generated {output_path}: {len(entries)} queries, "
          f"{len(blob_bytes)} bytes", file=sys.stderr)


if __name__ == "__main__":
    main()
